GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJNYXR0aGV3ICIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNzE3NTUzODMxLCJleHAiOjE3MTc1NTM4NDZ9.N7tNhmzvhgwvIbg0OVFinvkB9MhP1DQaAiIG_Zy79MA


###

POST  http://localhost:5000/users
Content-Type: application/json

{
"name" : "Matthew ",
"email" : "email@gmail.com",
"notelp" : "1619369619361",
"password" : "123456",
"confPassword" : "123456"
}
    
###

POST  http://localhost:5000/login
Content-Type: application/json

{
    "email" : "email@gmail.com",
    "password" : "123456"
}


###

GET  http://localhost:5000/token

###
DELETE  http://localhost:5000/logout